# Generated by Django 5.2.4 on 2025-07-12 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('is_featured', models.BooleanField(default=False, verbose_name='注目記事')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開状態')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'ordering': ['-created_at'],
            },
        ),
    ]
